apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ibi37c9yd-go 
  janus-idp.io/tekton: ibi37c9yd-go
  backstage.io/kubernetes-id: ibi37c9yd-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ibi37c9yd-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml