apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ibi37c9yd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ibi37c9yd-go 
  name: ibi37c9yd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ibi37c9yd-go 
